### ISSUE TITLE
Cannot reproduce the (average effect) Plot

### ISSUE THREAD

**Issue by zlqs1985** [ebenmichael/augsynth#26]
Hi, Eli:
     I'm trying to reproduce the results of your staggered adoption example. Everything just goes well except I cannot produce the plot of the average treatment effect. With command like 
`plot(ppool_syn_summ, level = "Average")`
the augsynth package can still produce the following plot some as `plot(ppool_syn_summ)`
My augsynth version is 0.2.0

**Comment by ebenmichael** [comment]
Sorry about that! It should be `levels = "Average"` not `level = "Average"`. I hadn't updated the vignette, but now it's updated thanks to #23
