### ISSUE TITLE
Control Units error

### ISSUE THREAD

**Issue by speedtriple955** [ebenmichael/augsynth#28]
Hello, 

I am running a model with multiple treated units. I get an error on this line because the `treated_unit` has multiple elements.
https://github.com/ebenmichael/augsynth/blob/8bd01b303752b4b0a3050f0bf26f292a4591d924/R/augsynth.R#L54

I fixed it by changing the control_units definition to:

control_units <- data %>% filter(!(!!unit %in% treated_unit)) %>% distinct(!!unit) %>% pull(!!unit)

**Comment by ebenmichael** [comment]
Thanks for catching that! I just updated the code with that change.

Let me know if you find more bugs, and if you also find fixes definitely feel free to make a PR with the fix!
