### ISSUE TITLE
predict() command has two different modes

### ISSUE THREAD

**Issue by lmiratrix** [ebenmichael/augsynth#33]
It appears as if predict( acsm, att=TRUE ) gives a different output than predict( acsm, att=FALSE ).  Is that by design?

```
> p1 = predict( syn, att=TRUE )
> class( p1 )
[1] "numeric"
> p2 = predict( syn, att=FALSE )
> class( p2 )
[1] "matrix"
```

**Comment by ebenmichael** [comment]
I finally got to this! It was not by design, and it turns out leading to unnecessary code. Now everything should be a numeric vector.

**Comment by lmiratrix** [comment]
nice!

      --> Due to my RSI (wrist trouble), e-mail often abrupt <--
