### ISSUE TITLE
Error in augsynth command

### ISSUE THREAD

**Issue by aghosh19** [ebenmichael/augsynth#4]
Hello, I am having an issue to run the augsynth package in my data. Is there anyway to fix this? Thank you very much. The error is as follows:
 > library(augsynth)
> options(error=utils::recover)
> syn <- augsynth(Y ~ Treatment | cov1 + cov2, region, year, 1996, data, progfunc="None", weightfunc="SCM")
**Error in X[trt == 0, , drop = F] : (subscript) logical subscript too long**

Enter a frame number, or 0 to exit   

1: augsynth(propM ~ Codelaw | inc + UR, STATEID, YEAR, 1996, asynthcali, progfunc = "None"
2: do.call(format_synth, wide)
3: (function (X, trt, y) 
{
    synth_data <- list()
    synth_data$Z0 <- t(X[trt == 0, , 
4: t(X[trt == 0, , drop = F])

Selection: 4
Called from: t(X[trt == 0, , drop = F])
Browse[1]>

**Comment by ebenmichael** [comment]
Sorry for the unhelpful error message, I'll change that. 

After playing around a bit, I think you're getting this error because your data doesn't contain any pre-intervention data. Could you double check to see if that's the case?

**Comment by aghosh19** [comment]
Thank you very much for getting back to me. My data does have pre-intervention data. After trying a few more things to fix it, it seemed to me that the error might have been because my panel data was unbalanced. Not sure if this is the answer though but do please let me know your thoughts. I am sorry if this is indeed the answer and I might have missed a note somewhere which discusses about this.

**Comment by ebenmichael** [comment]
Yeah currently none of the SCM methods or extensions work with unbalanced panels, but hopefully will at some point soon! I'll add a check for that to save people frustration in the future, thanks for bringing it up.
