### ISSUE TITLE
Jackknife+

### ISSUE THREAD

**Issue by azev77** [ebenmichael/augsynth#40]
I'm having a little trouble understanding appendix B of [your paper](https://arxiv.org/pdf/1811.04170.pdf). 

For Jackknife+:
LOO residuals: <img width="96" alt="image" src="https://user-images.githubusercontent.com/7883904/107728864-3d6b6800-6cbd-11eb-9fba-9b0bed2fbd27.png">
Estimated post-treatment outcome (w/o period "t"): <img width="45" alt="image" src="https://user-images.githubusercontent.com/7883904/107728921-63910800-6cbd-11eb-8c9b-0cfe2ac66290.png">

PI: <img width="615" alt="image" src="https://user-images.githubusercontent.com/7883904/107729102-eade7b80-6cbd-11eb-9d7b-43ce99a25d2c.png">
I'm confused b/c the following quantity varies w/ dropped-period "t": <img width="188" alt="image" src="https://user-images.githubusercontent.com/7883904/107729029-ab179400-6cbd-11eb-8757-7277035f1f4a.png">
Which dropped period "t" is used?
Or is this quantity averaged across all t in 1:T0?

**Update**:
for each t in 1:T0, compute x_t = <img width="188" alt="image" src="https://user-images.githubusercontent.com/7883904/107729029-ab179400-6cbd-11eb-8757-7277035f1f4a.png">
Then use this to compute the order-stat for x_1 to x_T0: <img width="72" alt="image" src="https://user-images.githubusercontent.com/7883904/107730119-b61ff380-6cc0-11eb-83f2-771a59969493.png">
Then is this a typo?:<img width="299" alt="image" src="https://user-images.githubusercontent.com/7883904/107730231-df408400-6cc0-11eb-927e-feb8fe14bc28.png">

**Comment by ebenmichael** [comment]
You're right that the quantity varies with the dropped time period. For each time period that we drop, we compute the LOO residual for that time period and the post-treatment outcome, dropping out that time period. We then take the alpha and 1-alpha quantiles as defined.

The intuition for why we want to re-compute the post-treatment estimate is spelled out in Fig 1 of the [paper](https://arxiv.org/abs/1905.02928) we cite.
