### ISSUE TITLE
Error in mask[j, ] : subscript out of bounds

### ISSUE THREAD

**Issue by mmbanasaz** [ebenmichael/augsynth#42]
Hi there
I am using the package for a monthly database, and I want to compile the 'multisynth' function. I am getting this error:
"Error in mask[j, ] : subscript out of bounds"
Recently, I used the function for a yearly database, and I don't have any issues. Could it be from the 'date' variable?
I wondered if you have any thoughts on what that error is related to? 

Thanks

**Comment by ebenmichael** [comment]
Could you tell me more about the structure of data? Is it a balanced panel? Also it'd be helpful to see the stack trace via `traceback` (but sometimes this shows all the data and becomes totally useless)

**Comment by mmbanasaz** [comment]
Thank you. I trimmed data a little, and there is no issue now.  I think the panel was not balanced.
