### ISSUE TITLE
Already treated people as control group

### ISSUE THREAD

**Issue by mmbanasaz** [ebenmichael/augsynth#44]
Hi
According to your paper, the package is using not-treated and no-yet-treated individuals as controls.
Is there any way in the package to use already-treated people as controls, too, resembling a TWFE control group?  

Thanks - Mo

**Comment by ebenmichael** [comment]
Do you mean to do this to estimate the treatment effect on the controls? The package doesn't implement that unfortunately.

**Comment by mmbanasaz** [comment]
No problem. Thanks
