### ISSUE TITLE
A problem with augsynth() command

### ISSUE THREAD

**Issue by julinka14** [ebenmichael/augsynth#47]
Hello,

thank you for all the great work on this package. I ran into a issue with a command augsynth() and I have no luck solving it. When I try to run:

asyn <- augsynth(Master_data_df_balanced$gdppc ~ Master_data_df_balanced$treated, Master_data_df_balanced$country_no, Master_data_df_balanced$year, 2014, Master_data_df_balanced)

I am getting error message:

Error in UseMethod("group_by") : 
  no applicable method for 'group_by' applied to an object of class "c('double', 'numeric')"

Frankly, I do not understand where the problem lies. This is how my dataframe looks like:
![image](https://user-images.githubusercontent.com/83948247/117630127-2a144f80-b17b-11eb-9091-3d800c0a72a1.png)

I am still learning how to work with R and I am sorry if this is trivial question. Any suggestions are appreciated.
Thank you!

**Comment by julinka14** [comment]
Thank you very much for your quick answer. I tried your suggestion, but I got the same error message. I tried to google it again with no luck. Then I tried to run similar command but with function single_augsynth() :

asyn <- single_augsynth(gdppc ~ treated, country_no, year, 2014, Master_data_df_balanced, progfunc="None")

I do not know why, but this solution worked for me!

**Comment by ebenmichael** [comment]
Ok glad it's working with `single_augsynth`, although it shouldn't be any different! Is there only one treated unit or are there multiple treated units with simultaneous adoption? That'll help me track down if there's a bug.
