### ISSUE TITLE
Estimates are not invariant to sort order

### ISSUE THREAD

**Issue by davidnathanlang** [ebenmichael/augsynth#54]
Running the example code generates distinct results based on the way the data is fed into the augsynth. It generates point estimates that are pretty different. Here's an example using the code from your vignette. 

```
library(augsynth)
library(dplyr)
data(kansas)
(
syn1 <- augsynth(lngdpcapita ~ treated, fips, year_qtr,   # Vignette Example  Estimate -0.029
                 kansas,
                 progfunc = "None", scm = T)
)
(syn2 <- augsynth(lngdpcapita ~ treated, fips, year_qtr,  #Descending Estimate -0.008
                 kansas %>% arrange(fips,desc(year_qtr)),
                 progfunc = "None", scm = T)
)

```

**Comment by ebenmichael** [comment]
Thanks for catching this! In this case there was a bug in how the function was picking the treatment time when it wasn't provided by the user. It should be fixed now!
