### ISSUE TITLE
Parenthesis causes different CI's

### ISSUE THREAD

**Issue by santideambrosi** [ebenmichael/augsynth#61]
Hello Ben, I am getting different confidence intervals depending on whether or not I insert a parenthesis on the outcome of interest--is this an error? The estimate remains the same regardless.
        

> summary(augsynth::augsynth(gsa_mi ~ treatment, state, year, 2017, data=nphi_gsa, weightfunc="ASCM"))
> 
> One outcome and one treatment time found. Running single_augsynth.
> 
> Call:
> single_augsynth(form = form, unit = !!enquo(unit), time = !!enquo(time), 
>     t_int = t_int, data = data, weightfunc = "ASCM")
> 
> Average ATT Estimate (p Value for Joint Null):  0.137   ( 0.505 )
> L2 Imbalance: 0.050
> Percent improvement from uniform weights: 72.1%
> 
> Avg Estimated Bias: 0.010
> 
> Inference type: Conformal inference
> 
>  Time Estimate 95% CI Lower Bound 95% CI Upper Bound p Value
>  2016   -0.006                 NA                 NA      NA
>  2018    0.137             -0.137              0.412     0.5
> There were 50 or more warnings (use warnings() to see the first 50)

But this differs from the following specification, where I add a parenthesis to ...augsynth(**(**gsa_mi**)**~...

> summary(augsynth::augsynth((gsa_mi) ~ treatment, state, year, 2017, data=nphi_gsa, weightfunc="ASCM"))
> 
> Multiple outcomes and one treatment time found. Running augsynth_multiout.
> 
> Call:
> augsynth_multiout(form = form, unit = !!enquo(unit), time = !!enquo(time), 
>     t_int = t_int, data = data, weightfunc = "ASCM")
> 
> Overall L2 Imbalance (Scaled):0.050  (0.279)
> 
> Average ATT Estimate:
>   Outcome  Estimate  Std.Error   Pre.RMSE
> 1  gsa_mi 0.1372524 0.08831002 0.02253471
> 
> There were 20 warnings (use warnings() to see them)

I should add that I only have one post-intervention observation (2018), and 5 pre-intervention observations (2008-2016, bianually). The intervention happened in 2017. My interpretation is that the big CI is due to the few pre-intervention observations.

**Comment by santideambrosi** [comment]
The plot(...) also changes the graphic: when parenthesis are included, the title of the outome appears in the graph.

- With no parenthesis:

<img width="367" alt="Screen Shot 2021-09-22 at 6 08 09 PM" src="https://user-images.githubusercontent.com/80441500/134428613-f110e93a-5db6-4c4b-a3a5-e7d65b15f709.png">

- With parenthesis:

<img width="369" alt="Screen Shot 2021-09-22 at 6 08 32 PM" src="https://user-images.githubusercontent.com/80441500/134428644-f03c324a-aead-4e5f-a916-ec71f26c3c84.png">

**Comment by davidnathanlang** [comment]
The addition of the parentheses calls a different function.  
The first calls  `single_augsynth` 
The second uses  multi_synth.

Single augsynth defaults to conformal inference as it's preferred inference strategy.

Multi synth uses a wild bootstrap.   
This difference is to be expected.

**Comment by santideambrosi** [comment]
Thank you, David!
