### ISSUE TITLE
conformal_inf 

### ISSUE THREAD

**Issue by stmicha** [ebenmichael/augsynth#65]
Hello,
I am trying to run the conformal_inf function and I get the following error:
Error in conformal_inf(asyn, alpha = 0.05, type = "iid", q = 1, ns = 1000,  : 
  could not find function "conformal_inf"

**Comment by davidnathanlang** [comment]
I don't think there's a conformal_inf function that is public. If you have already trained the augsynth model, you can specify the inference type via the summary  function 

e.g.
summary(asyn,inf_type="conformal")
