### ISSUE TITLE
Issues with `replace_na()` in tidyr v1.2.0

### ISSUE THREAD

**Issue by ArturoEsquerra** [ebenmichael/augsynth#68]
Hi everyone!

We just noticed that a change in the newly released version of `tidyr` (v1.2.0) causes a problem with `augsynth()`. 

Specifically, in the new version of tidyr, the `replace_na()` function no longer allows the type of `data` to change (more info on this change can be found [here](https://tidyr.tidyverse.org/news/index.html)). Therefore, replacing NA's of the integer column `trt_time` with `Inf`  through the line: `mutate(trt_time = replace_na(trt_time, Inf))` makes the code crash as `replace_na()` can't no longer convert from double to integer.

Best.
Arturo

**Comment by ebenmichael** [comment]
Thanks for catching this! Can you link to the relevant line? Would it fix things to make sure that the treatment time is a double?

**Comment by ArturoEsquerra** [comment]
Thanks for the quick reply! Matching the data types of `trt_time` and the replacement value should fix the issue.

I believe that the that the affected lines are:
1. [Line 61](https://github.com/ebenmichael/augsynth/blob/master/R/augsynth_pre.R#L61) of `augsynth_pre.R`
2. [Line 104](https://github.com/ebenmichael/augsynth/blob/master/R/format.R#L104) of `format.R` (potentially line 156 of the same .R file as well)

**Comment by idg23** [comment]
Is this issue solved? Thanks in advance!

**Comment by ebenmichael** [comment]
Sorry for the delay here, this should be fixed now!
