### ISSUE TITLE
Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102

### ISSUE THREAD

**Issue by Abel73** [ebenmichael/augsynth#73]
When I was trying to fit a model with large units (e.g., over 100,000 units and around 30 time periods), the function failed adn reported:

Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102

I think this might because of very large dense matric created during process and hopefully this method could be solved in the future.

Thank you!

**Comment by ebenmichael** [comment]
Thanks for flagging this. As of now, the code isn't really set up to solve problems that large. But, if you set `time_cohort = TRUE` it'll collapse units into individual time cohorts, and then the problem might not be too large to solve.
