### ISSUE TITLE
how to interpret the results obtain with multisynth

### ISSUE THREAD

**Issue by FranInostroza0206** [ebenmichael/augsynth#74]
Hello, 

I´m working on my thesis with this package and I wonder if you could explain to me how to interpretthe results obtain in the given example.

![image](https://user-images.githubusercontent.com/104450203/165341807-820d66cc-aea6-4fe7-8325-6f835d26b1e1.png)

Thanks in advance!!

**Comment by ebenmichael** [comment]
The first line shows the overall average effect on the treated units, averaged over post-treatment times. The next set of numbers shows the square root of the sum of the squared errors on the pre-treatment outcomes both on average, and for the units individually. The last set of numbers breaks down the effects by time after treatment.

**Comment by anzonyquispe** [comment]
> The first line shows the overall average effect on the treated units, averaged over post-treatment times. The next set of numbers shows the square root of the sum of the squared errors on the pre-treatment outcomes both on average, and for the units individually. The last set of numbers breaks down the effects by time after treatment.

Sorry for re-oppening this thread. I just want to be sure about the base year of event time. According to the paper, I am assuming that the base year is 0 . I mean we are getting estimates comparing with t-Tj = 0 or like some event study plots using lead = -1 using the period before as a comparing year.
![image](https://github.com/ebenmichael/augsynth/assets/69997588/4b3df525-277a-4715-b346-5d6eb523bdb7)
