### ISSUE TITLE
Examples for SCM with staggered adoption 

### ISSUE THREAD

**Issue by versatile712** [ebenmichael/augsynth#87]
Hi, thanks for your wonderful package. I am using this package for SCM with multiple treatments at multiple times (staggered adoption). However, I cannot figure out how to use this package in this circumstance. The introduction about staggered settings does not include an example, much appreciated if you could add some examples.

**Comment by ebenmichael** [comment]
Unfortunately the package doesn't support multiple treatments at this time. There are still some methodological issues to work out!
