### ISSUE TITLE
Very ram consuming 

### ISSUE THREAD

**Issue by anzonyquispe** [ebenmichael/augsynth#92]
I am using the code with a very large data and it is consuming too much ram. Does it normal to happens? I have 647549 units and 22 periods. Also I have treatment 9 years of treatment. I am working with a cluster and I set the ram 1Tb and 2Tb and it still crush because it is out of memory. I would like to know if it may be happen or I am doing something wrong. I would like to add that the panel is balance.

**Comment by ebenmichael** [comment]
By default, `multisynth` will have one set of weights for each treated unit, creating a matrix of weights that is (number of treated units) x (total number of units). In your case that will be very large.

For large data problems, you can collapse into treatment-time cohorts (e.g. [see the vignette here](https://github.com/ebenmichael/augsynth/blob/master/vignettes/multisynth-vignette.md#collapsing-into-time-cohorts)). This will make one set of weights for each treatment-time cohort (I think 9 in your case), so the weight matrix will be 9 x 647,549.

**Comment by anzonyquispe** [comment]
Thanks for this information.!!!

**Comment by anzonyquispe** [comment]
Does it have any implication in interpretations?
